export const dataToTable = [
    {
        id: 1000,
        name: 'James Butt',
        country: { name: 'Algeria', code: 'dz' },
        company: 'Benton, John B Jr',
        date: '2015-09-13',
        status: 'unqualified',
        verified: true,
        activity: 17,
        representative: { name: 'Ioni Bowcher', image: 'ionibowcher.png' },
        balance: 70663
    },
    {
        id: 1001,
        name: 'Josephine Darakjy',
        country: { name: 'Egypt', code: 'eg' },
        company: 'Chanay, Jeffrey A Esq',
        date: '2019-03-11',
        status: 'qualified',
        verified: false,
        activity: 30,
        representative: { name: 'Amy Elsner', image: 'amyelsner.png' },
        balance: 12345
    },
    {
        id: 1002,
        name: 'Art Venere',
        country: { name: 'Morocco', code: 'ma' },
        company: 'Chemel, James L Cpa',
        date: '2020-01-19',
        status: 'new',
        verified: true,
        activity: 5,
        representative: { name: 'Asiya Javayant', image: 'asiyajavayant.png' },
        balance: 78900
    },
    {
        id: 1003,
        name: 'Lenna Paprocki',
        country: { name: 'Kenya', code: 'ke' },
        company: 'Feltz Printing Service',
        date: '2021-06-10',
        status: 'proposal',
        verified: false,
        activity: 12,
        representative: { name: 'Brandon Smith', image: 'brandonsmith.png' },
        balance: 51200
    },
    {
        id: 1004,
        name: 'Donette Foller',
        country: { name: 'Argentina', code: 'ar' },
        company: 'Printing Dimensions',
        date: '2022-07-08',
        status: 'renewal',
        verified: true,
        activity: 21,
        representative: { name: 'Samantha May', image: 'samanthamay.png' },
        balance: 41300
    },
    {
        id: 1005,
        name: 'Simona Morasca',
        country: { name: 'Brazil', code: 'br' },
        company: 'Chapman, Ross E Esq',
        date: '2018-11-03',
        status: 'qualified',
        verified: false,
        activity: 14,
        representative: { name: 'Kiyoshi Zane', image: 'kiyoshizane.png' },
        balance: 63800
    },
    {
        id: 1006,
        name: 'Mitsue Tollner',
        country: { name: 'Canada', code: 'ca' },
        company: 'Morlong Associates',
        date: '2016-04-21',
        status: 'unqualified',
        verified: true,
        activity: 20,
        representative: { name: 'Asiya Javayant', image: 'asiyajavayant.png' },
        balance: 52000
    },
    {
        id: 1007,
        name: 'Leota Dilliard',
        country: { name: 'Germany', code: 'de' },
        company: 'Commercial Press',
        date: '2017-09-09',
        status: 'renewal',
        verified: false,
        activity: 10,
        representative: { name: 'Amy Elsner', image: 'amyelsner.png' },
        balance: 49500
    },
    {
        id: 1008,
        name: 'Sage Wieser',
        country: { name: 'France', code: 'fr' },
        company: 'Truhlar And Truhlar Attys',
        date: '2021-12-15',
        status: 'proposal',
        verified: true,
        activity: 28,
        representative: { name: 'Brandon Smith', image: 'brandonsmith.png' },
        balance: 57400
    },
    {
        id: 1009,
        name: 'Kris Marrier',
        country: { name: 'Italy', code: 'it' },
        company: 'King, Christopher A Esq',
        date: '2020-05-05',
        status: 'new',
        verified: false,
        activity: 11,
        representative: { name: 'Ioni Bowcher', image: 'ionibowcher.png' },
        balance: 31000
    },
    {
        id: 1010,
        name: 'Minna Amigon',
        country: { name: 'Japan', code: 'jp' },
        company: 'Dorl, James J Esq',
        date: '2019-08-20',
        status: 'unqualified',
        verified: true,
        activity: 19,
        representative: { name: 'Kiyoshi Zane', image: 'kiyoshizane.png' },
        balance: 63000
    },
    {
        id: 1011,
        name: 'Abel Maclead',
        country: { name: 'Mexico', code: 'mx' },
        company: 'Rangoni Of Florence',
        date: '2018-01-30',
        status: 'proposal',
        verified: false,
        activity: 8,
        representative: { name: 'Samantha May', image: 'samanthamay.png' },
        balance: 49520
    },
    {
        id: 1012,
        name: 'Kiley Caldarera',
        country: { name: 'Spain', code: 'es' },
        company: 'Feiner Bros',
        date: '2023-02-14',
        status: 'qualified',
        verified: true,
        activity: 23,
        representative: { name: 'Amy Elsner', image: 'amyelsner.png' },
        balance: 72600
    },
    {
        id: 1013,
        name: 'Graciela Ruta',
        country: { name: 'Portugal', code: 'pt' },
        company: 'Press Room',
        date: '2022-09-30',
        status: 'renewal',
        verified: true,
        activity: 16,
        representative: { name: 'Brandon Smith', image: 'brandonsmith.png' },
        balance: 48800
    },
    {
        id: 1014,
        name: 'Cammy Albares',
        country: { name: 'Norway', code: 'no' },
        company: 'Curry & Friend',
        date: '2020-10-10',
        status: 'new',
        verified: false,
        activity: 7,
        representative: { name: 'Ioni Bowcher', image: 'ionibowcher.png' },
        balance: 33000
    },
    {
        id: 1015,
        name: 'Sonya Wages',
        country: { name: 'Sweden', code: 'se' },
        company: 'Igoe, Daniel J Esq',
        date: '2021-04-04',
        status: 'qualified',
        verified: true,
        activity: 25,
        representative: { name: 'Asiya Javayant', image: 'asiyajavayant.png' },
        balance: 59000
    },
    {
        id: 1016,
        name: 'Emery Pople',
        country: { name: 'Finland', code: 'fi' },
        company: 'Levinson Axelrod',
        date: '2022-11-22',
        status: 'proposal',
        verified: false,
        activity: 6,
        representative: { name: 'Amy Elsner', image: 'amyelsner.png' },
        balance: 42000
    },
    {
        id: 1017,
        name: 'Luciano Langston',
        country: { name: 'Iceland', code: 'is' },
        company: 'Koepp Inc',
        date: '2020-06-18',
        status: 'new',
        verified: true,
        activity: 9,
        representative: { name: 'Brandon Smith', image: 'brandonsmith.png' },
        balance: 30800
    },
    {
        id: 1018,
        name: 'Andre Callas',
        country: { name: 'India', code: 'in' },
        company: 'Johnson, David Esq',
        date: '2017-12-01',
        status: 'unqualified',
        verified: false,
        activity: 18,
        representative: { name: 'Kiyoshi Zane', image: 'kiyoshizane.png' },
        balance: 37700
    },
    {
        id: 1019,
        name: 'Sibyl Stoecker',
        country: { name: 'China', code: 'cn' },
        company: 'Rosenblatt, James Esq',
        date: '2019-03-27',
        status: 'qualified',
        verified: true,
        activity: 26,
        representative: { name: 'Ioni Bowcher', image: 'ionibowcher.png' },
        balance: 58300
    },
    {
        id: 1020,
        name: 'Billie Brister',
        country: { name: 'Australia', code: 'au' },
        company: 'Wood, Christopher A Esq',
        date: '2023-01-15',
        status: 'proposal',
        verified: false,
        activity: 13,
        representative: { name: 'Amy Elsner', image: 'amyelsner.png' },
        balance: 46900
    },
    {
        id: 1021,
        name: 'Holli Waterhouse',
        country: { name: 'New Zealand', code: 'nz' },
        company: 'Oceanic Law Firm',
        date: '2022-04-28',
        status: 'renewal',
        verified: true,
        activity: 27,
        representative: { name: 'Brandon Smith', image: 'brandonsmith.png' },
        balance: 65000
    },
    {
        id: 1022,
        name: 'Quinn Lupo',
        country: { name: 'Peru', code: 'pe' },
        company: 'LegalGroup Lima',
        date: '2021-08-05',
        status: 'new',
        verified: false,
        activity: 15,
        representative: { name: 'Samantha May', image: 'samanthamay.png' },
        balance: 35900
    },
    {
        id: 1023,
        name: 'Evangelina Dancy',
        country: { name: 'Colombia', code: 'co' },
        company: 'Andina Legal Services',
        date: '2020-02-11',
        status: 'unqualified',
        verified: true,
        activity: 22,
        representative: { name: 'Asiya Javayant', image: 'asiyajavayant.png' },
        balance: 72000
    },
    {
        id: 1024,
        name: 'Margarita Leddy',
        country: { name: 'South Africa', code: 'za' },
        company: 'Southern Law Solutions',
        date: '2019-10-17',
        status: 'qualified',
        verified: false,
        activity: 29,
        representative: { name: 'Ioni Bowcher', image: 'ionibowcher.png' },
        balance: 41000
    },
    {
        id: 1025,
        name: 'Armand Martella',
        country: { name: 'Chile', code: 'cl' },
        company: 'Martella & Partners',
        date: '2023-03-09',
        status: 'proposal',
        verified: true,
        activity: 24,
        representative: { name: 'Amy Elsner', image: 'amyelsner.png' },
        balance: 70200
    },
    {
        id: 1026,
        name: 'Tanya Chill',
        country: { name: 'Uruguay', code: 'uy' },
        company: 'Chill Legal Group',
        date: '2022-06-16',
        status: 'new',
        verified: false,
        activity: 4,
        representative: { name: 'Kiyoshi Zane', image: 'kiyoshizane.png' },
        balance: 38900
    },
    {
        id: 1027,
        name: 'Blake Trezza',
        country: { name: 'Denmark', code: 'dk' },
        company: 'Trezza & Co.',
        date: '2020-09-23',
        status: 'renewal',
        verified: true,
        activity: 32,
        representative: { name: 'Brandon Smith', image: 'brandonsmith.png' },
        balance: 67500
    },
    {
        id: 1028,
        name: 'Mindy Gualtieri',
        country: { name: 'Netherlands', code: 'nl' },
        company: 'Gualtieri Advocaten',
        date: '2021-07-07',
        status: 'qualified',
        verified: false,
        activity: 31,
        representative: { name: 'Samantha May', image: 'samanthamay.png' },
        balance: 56000
    },
    {
        id: 1029,
        name: 'Fred Mancuso',
        country: { name: 'Belgium', code: 'be' },
        company: 'Mancuso Legal',
        date: '2022-10-30',
        status: 'proposal',
        verified: true,
        activity: 33,
        representative: { name: 'Ioni Bowcher', image: 'ionibowcher.png' },
        balance: 48000
    }
];
